# Generated by Django 5.1.1 on 2024-09-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_rename_phone_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='discount_percentage',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
