# Generated by Django 5.1.7 on 2025-03-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_user_alter_wishlist_user'),
    ]

    operations = [
    ]
