# Generated by Django 5.1.7 on 2025-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_promotion_description_promotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
