# Generated by Django 5.1.7 on 2025-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_transaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
