# Generated by Django 5.1.7 on 2025-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_transaction_is_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='link',
        ),
        migrations.AddField(
            model_name='promotion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
