# Generated by Django 5.1.7 on 2025-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_transaction_link_promotion_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_hero',
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
