# Generated by Django 5.1.1 on 2025-03-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productspecification_producttype_and_more'),
        ('vendors', '0002_gestionnaire_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.gestionnaire'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttype'),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'key')},
        ),
    ]
